Repository devcsp/front-end-admin, pull requests merged in 2020-01, with the labels that each got.

#4 Add pull request template
  pull_request_template.md
Labels: docs

#1 Add editorconfig file
  .editorconfig
Labels: chore

#3 Automate commits pattern
  commitlint.config.js
  package-lock.json
  package.json
Labels: chore

#6 Add missing trailing comma
  package-lock.json
  package.json
Labels: fix

#7 Add auth in routes
  package.json
  src/App.js
  src/components/Navbars/DemoNavbar.jsx
  src/index.js
  src/layouts/Admin/Admin.js
  src/layouts/Admin/index.js
  src/routes.js
  src/routes/Route.js
  src/routes/adminRoutes.js
  src/routes/index.js
  src/services/history.js
  src/views/SignIn/SignIn.js
  src/views/SignIn/index.js
  src/views/Users/Users.js
  src/views/Users/index.js
  yarn.lock
Labels: improvement, refactor
